In [2]:
import numpy as np
from sklearn.isotonic import IsotonicRegression
from wave_cluster import Unimodal, error_tables

%load_ext autoreload
%autoreload 2

In [15]:
y = np.array([0,1,0,1,0])
unifit = Unimodal()
error, fitted_segment = unifit.fit_isotonic_segment(y, t1 = 0, t2 = 1, increasing = True)

In [16]:
fitted_segment

array([0.])

In [17]:
error

np.float64(0.0)

In [11]:
np.linalg.norm(y - fitted_segment)

np.float64(1.0)

In [11]:
iso_reg = IsotonicRegression(increasing = True).fit(np.array(range(5)), y)
iso_reg.predict(np.array([0,1,2,3,4]))

array([ 2.,  4.,  6.,  8., 10.])

In [3]:
error_tables(y)

(array([[nan,  0.,  0.,  0.,  0.,  0.],
        [ 0., nan,  0.,  0.,  0.,  0.],
        [ 0.,  0., nan,  0.,  0.,  0.],
        [ 0.,  0.,  0., nan,  0.,  0.],
        [ 0.,  0.,  0.,  0., nan,  0.]]),
 array([[       nan, 0.        , 1.41421356, 2.82842712, 4.47213595,
         6.32455532],
        [0.        ,        nan, 0.        , 1.41421356, 2.82842712,
         4.47213595],
        [0.        , 0.        ,        nan, 0.        , 1.41421356,
         2.82842712],
        [0.        , 0.        , 0.        ,        nan, 0.        ,
         1.41421356],
        [0.        , 0.        , 0.        , 0.        ,        nan,
         0.        ]]))

In [6]:
unifit.fit(np.array([2,4,6,4,2]), inflections = np.array([0,2,5]))

([np.float64(0.0), np.float64(0.0)], array([2., 4., 6., 4., 2.]))

In [10]:
error

np.float64(0.0)

In [9]:
fitted_segment

array([2.])